update makefiles, add gen-depend for offline automatic dependency generation

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -36,8 +36,11 @@ all: dummy version error $(ALL_TESTS)
 # for when $(TESTS) is empty
 # also checks that HKSC was set properly
 dummy:
-	@$(HKSC) --version >/dev/null 2>&1 || \
-	echo You need to set HKSC_NAME in the parent Makefile && false
+	@ if $(HKSC) --version >/dev/null 2>&1; then \
+		echo "using HKSC=$(HKSC)"; \
+	else \
+		echo "Invalid program name HKSC=$(HKSC)"; exit 1; \
+	fi
 
 # check version of $(HKSC) against expected version
 version:
@@ -84,7 +87,7 @@ error:
 	@: echo hello $@
 
 clean:
-	$(RM) *.luac *.luadebug *.luacallstackdb *.ctest *.dtest
+	@$(RM) *.luac *.luadebug *.luacallstackdb *.ctest *.dtest
 	@cd error && $(MAKE) $@
 
 .PHONY: test all dummy clean version error
diff --git a/test/error/Makefile b/test/error/Makefile
--- a/test/error/Makefile
+++ b/test/error/Makefile
@@ -20,7 +20,7 @@ YESHSTRUCTURE_TESTS=
 
 ALL_ERROR_TESTS= $(OTHER_TESTS) $(BOM_TESTS)
 
-all: prepare $(ALL_ERROR_TESTS) $(HSTRUCTURE_ERROR_TESTS)
+all: prepare $(ALL_ERROR_TESTS) $(HSTRUCTURE_ERROR_CHECK)
 	@printf 'All Lua error checks passed\n\n'
 
 prepare: clean
@@ -38,8 +38,14 @@ yeshstructure: $(YESHSTRUCTURE_TESTS)
 .expect.test:
 	@echo ------------ $* ------------
 	@EXTRAFLAGS= ; test "x$@" = "xliteraloverflow.test" && EXTRAFLAGS=-L; \
-	$(HKSC) $(HKSCFLAGS) $$EXTRAFLAGS $*.lua >/dev/null 2>$@
-	@if diff -Nbu $^ $@ ; then echo "$* test OK"; fi
+	if $(HKSC) $(HKSCFLAGS) $$EXTRAFLAGS $*.lua >/dev/null 2>$@; then \
+		echo "$*.lua error check failed (no error was raised)"; exit 1; \
+	else \
+		if diff -u $< $@; then echo "$*.lua error check OK"; \
+		else echo "$*.lua error check failed (output differs from expected)"; \
+			exit 1; \
+		fi; \
+	fi
 
 clean:
 	-@$(RM) *.test >/dev/null 2>&1
